# With some help from: https://gist.github.com/dgerosa/2e1f47a39180f39bde848e38243efa94

name: build
on:
  push:
    path: cv/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: cv
        uses: dante-ev/latex-action@latest
        with:
          root_file: cv
          working_directory: cv
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: "*.pdf"

      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: cv
